# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft/service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'raft/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12raft/service.proto\x12\x04raft\"_\n\x0fRequestVoteArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"5\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"D\n\x11\x41ppendEntriesArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x0f\n\x07\x65ntries\x18\x03 \x03(\t\"3\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"4\n\x0fResponseMessage\x12\x10\n\x08senderId\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0bResponseAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc2\x01\n\x04Raft\x12<\n\x0bRequestVote\x12\x15.raft.RequestVoteArgs\x1a\x16.raft.RequestVoteReply\x12\x42\n\rAppendEntries\x12\x17.raft.AppendEntriesArgs\x1a\x18.raft.AppendEntriesReply\x12\x38\n\x0cSendResponse\x12\x15.raft.ResponseMessage\x1a\x11.raft.ResponseAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTVOTEARGS']._serialized_start=28
  _globals['_REQUESTVOTEARGS']._serialized_end=123
  _globals['_REQUESTVOTEREPLY']._serialized_start=125
  _globals['_REQUESTVOTEREPLY']._serialized_end=178
  _globals['_APPENDENTRIESARGS']._serialized_start=180
  _globals['_APPENDENTRIESARGS']._serialized_end=248
  _globals['_APPENDENTRIESREPLY']._serialized_start=250
  _globals['_APPENDENTRIESREPLY']._serialized_end=301
  _globals['_RESPONSEMESSAGE']._serialized_start=303
  _globals['_RESPONSEMESSAGE']._serialized_end=355
  _globals['_RESPONSEACK']._serialized_start=357
  _globals['_RESPONSEACK']._serialized_end=387
  _globals['_RAFT']._serialized_start=390
  _globals['_RAFT']._serialized_end=584
# @@protoc_insertion_point(module_scope)
